version: 2

models:
  - name: transformed_customers
    description: "Cleaned and deduplicated customer data"
    columns:
      - name: customer_id
        tests:
          - unique
          - not_null
      - name: full_name
        tests:
          - not_null
