version: 2

models:
  - name: clean_customers
    description: "Customer table with standardized data"
    tests:
      - unique:
          column_name: customer_id
      - not_null:
          column_name: full_name

  - name: clean_sales_fact
    description: "Fact table for sales data"
    tests:
      - not_null:
          column_name: total_revenue
